pipeline {
  agent any
  stages {
    stage('Preparation') {
      steps {
        checkout scm
        sh "git rev-parse --short HEAD > .git/commit-id"
        def commit_id = readFile('.git/commit-id').trim()
      }
    }
    stage('test') {
      steps {
        nodejs(nodeJSInstallationName: 'nodejs') {
          sh "npm install --only=dev"
          sh "npm test"
        }
      }
    }
    stage("deocker build/push") {
      steps {
        docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
         def app = docker.build("bvenkatr/docker-nodejs-demo:${commit_id}", ".")
       }
      }
    }
  }
}
